### ISSUE TITLE
Mandatory fields need refining

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/Faraday-liionsden#118]
**Problem:** Many models can be saved without some info that seems as though it should be mandatory. E.g. "name". There may be a good reason that some models don't fundamentally have to have certain fields as mandatory, but it might be a good idea to review this.

**Proposed solution:**
- [x] Review the key models in BattDB and dfndb and make sure that if fields are not mandatory it makes sense.
- [x] If we decide to leave some fields as `null=True`, review whether this should be enforced in the front end in some cases. E.g. should a user be able to upload an Experiment with no "name" via the webapp form? This can be enforced at the form level if needed.
- [x] Also review unique-ness of important fields e.g. experiment names, batch names etc.

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-132-22

**Comment by AdrianDAlessandro** [comment]
Starting by reviewing what is visible in the forms. Some issues with saving forms with blank values in mandatory fields might be solved by the valid formset issue identified in https://github.com/ImperialCollegeLondon/Faraday-liionsden/pull/209#issuecomment-1320097556

Models and fields that should be mandatory (uncertain marked with "?"):

- Experiment:
  - [ ] Name
  - [ ] Thermal management - Currently mandatory, but includes a None option
  - [ ] Device-Batch - Currently mandatory but can include Null option
  - [ ] Experiment type and Thermal management? - both have an "Other" option - but detail to be included in the optional notes. Should the detail be made mandatory is other is selected?
  - [ ] Config? - mentions "all devices must be the same config" but allows Null option
  - [ ] Temperature? - should this not be in the data files?
- ExperimentDataFile:
  - [ ] Name - if left blank is given a name based on the file. I think this is good behaviour, but a note should be added to the form to say this.
  - [ ] Machine?
- Batch
  - [ ] Specification - Currently mandatory but includes a None option
  - [ ] SerialNo - Unique Identifier seems like it should be mandatory
- Device
  - [ ] Name
  - [ ] Type?
  - [ ] Parameter - Currently mandatory but allows a Null option
  - [ ] Component - Currently mandatory but allows a Null option
- Equipment
  - [ ] Name
  - [ ] SerialNo
  - [ ] Institution is mandatory, should it be?
- Component
  - [ ] Name
  - [ ] Composition-Compound - Currently mandatory but allows a Null option
  - [ ] Composition-Amount - Currently mandatory but allows a Null option
- Compound - everything is already mandatory

**Comment by dandavies99** [comment]
- Experiment:
  - [ ] Name - Mandatory and unique together with something? e.g. unique name+institution. Give useful error message if condition not met in frontend form. 
  - [ ] Thermal management - Not mandatory
  - [ ] Device Formset: Fields show as mandatory even though the formset itself is optional. E.g. you can add no devices to an experiment, but if you do add any devices then all three fields (Batch, Batch Sequence, Device Position) are mandatory. See below re: formsets. 
    - [ ] _Detail to be included in the optional notes. Should the detail be made mandatory is other is selected?_  - We can implement this if it's v little effort.
  - [ ] Experiment type and Thermal management? - both have an "Other" option - but detail to be included in the optional notes. This is fine but change thermal management "None" to "No thermal management" 
    - [ ] Specify in Summary not Notes if "other" selected.  
  - [ ] Config? - We should include a data migration for single cell and make this field mandatory for experiments. 
  - [ ] Temperature? - have as non-mandatory. 
- ExperimentDataFile:
  - [ ] Name - if left blank is given a name based on the file. I think this is good behaviour, but a note should be added to the form to say this in the help text. Leave as non-mandatory. 
  - [ ] Machine - leave as non-mandatory.
- Batch
  - [ ] Specification - Leave as is - it is and should be mandatory but null should be an option.
  - [ ] SerialNo - also should be unique and is not
- Device specification
  - [ ] Name - also should be unique and is not
  - [ ] Type?
  - [ ] Parameter - Currently mandatory but allows a Null option
  - [ ] Component - Currently mandatory but allows a Null option
- Equipment
  - [ ] Name - also should be unique and mandatory
  - [ ] SerialNo - Leave as is for now as batches well-defined by manufac-date-device combo.
  - [ ] Manufacturer (Organisation) - is mandatory and should be, but should be limited to "is mfg cells"
- Component
  - [ ] Name - also should be unique and mandatory
  - [ ] Composition-Compound - Currently mandatory but allows a Null option -see formset issue below
  - [ ] Composition-Amount - Currently mandatory but allows a Null option
- Compound
  - [ ] Name are Formula are unique together, but not individually and they should be. Then there is no need for them to be unique together. 

TODOs:
- New issue about behaviour of formsets - validation and mandatory fields etc.
