### ISSUE TITLE
Test robustness of existing parsers with more example files.

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/Faraday-liionsden#172]
# Problem

Currently, each new file introduced to the system has in some way broken it and we've responded by updating the code.

# Proposed solution

We should keep iterating this process with more example files to squash any more bugs.

We have a set of example files for the two parsers we have - Maccor and Biologic - [here in this sharepoint folder](https://imperiallondon.sharepoint.com/:f:/r/sites/RSE/Shared%20Documents/General/Projects/Liionsden/Sample%20data?csf=1&web=1&e=e0UOH0). Each of the files in those two folder should in theory be parsed successfully by the parsers we have.

**Steps to test:**

- Create a new experiment at `https://localhost:8000/battDB/new_experiment/`. It doesn't matter what is in any of the fields, a new experiment just has to exist. 
- On the details page for that experiment, click "Add more experimental data".
- Upload the file, being sure to select the right parser, and click "save". 
- If the file is parsed successfully, there should be a new preview of the data on the experiment details page like the screenshot below. If not, you will likely get an error message.

We can keep track of how successful each upload has been in this issue, pasting any error messages.

**Data preview should look similar to this:**

![Image](https://user-images.githubusercontent.com/5871253/193777065-a5c6cea2-4db9-451c-9490-cd9c24bcce40.png)

**Comment by CWestICL** [comment]
I've gone through and tested each of the example files. 5 of them produced errors when uploading, issues raised here:

- https://github.com/ImperialCollegeLondon/Faraday-liionsden/issues/185
- https://github.com/ImperialCollegeLondon/Faraday-liionsden/issues/186
- https://github.com/ImperialCollegeLondon/Faraday-liionsden/issues/188
- https://github.com/ImperialCollegeLondon/Faraday-liionsden/issues/190

**Comment by CWestICL** [comment]
Re-tested the example files and found that the following files do not show a preview of the data as expected when parsed:

- Group+10+-+Cell+25_02_MB_C03.mpt.csv
- sample_Maccor_2.xlsx
