### ISSUE TITLE
Additional file fields on ExperimentDataFile

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/Faraday-liionsden#179]
**Feature**
In the interest of reproducibility, it would be better to have the input script that is supplied to the cycler for each uploaded raw data file. That way, another researcher can use that input script to reproduce the experimental steps. This file does not have to be parsed in any way.

**Proposed solution**
- [x] Add an `input_script` file field on `ExperimentDataFile`
- [x] This file should be validated - must be a text file (not binary file) but probably can have any extension.
- [x] There should be another (optional) field on the form for "input script" when uploading a data file.
- [x] It makes sense to tackle the uploading of binary files at the same time - #83. This should be another optional field with no parsing needed.
  - [x] Create a new field for this
  - [x] Add a formfield for this (optional)

**Potential blockers**
- [x] What do the files look like? Get an example from the research team.

**Comment by kobistar** [comment]
@dandavies99 can I claim this issue?

**Comment by dandavies99** [comment]
We now have a sample input file we can use for this.

**Comment by dandavies99** [comment]
@kobistar are you still planning to work on this?

**Comment by kobistar** [comment]
Hi, yes I do, but I hlave trouble with start the project. Can you or
somebidy help me please?

Tahnks
Šimon Trebišovský

Dňa st 2. 11. 2022, 16:33 Dan Davies ***@***.***> napísal(a):

**Comment by dandavies99** [comment]
Hi @kobistar - With the most recent version of the code on the `develop` branch, if you have docker installed, you should be able to run `docker compose up --build` to start the application.

If you would rather not tackle this issue, that's also fine 😄

**Comment by dandavies99** [comment]
Still to do:
- Buttons to download the new two files
- Use generate_sas_token() to download new files
- Tests for new validators
- Update Tests for new model fields
- Update tests for new views
