### ISSUE TITLE
No preview for Biologic example file - Group+10+-+Cell+25_02_MB_C03.mpr

### ISSUE THREAD

**Issue by CWestICL** [ImperialCollegeLondon/Faraday-liionsden#190]
**Describe the issue**
Uploading the example file Group+10+-+Cell+25_02_MB_C03.mpr with the Biologic parser resulted in no preview for file data.

**To Reproduce**
Steps to reproduce the behaviour:
1. Uploaded Group+10+-+Cell+25_02_MB_C03.mpr using the Biologic parser
2. Upload passes successfully but there is not data in the preview

**Screenshot**
![image](https://user-images.githubusercontent.com/108276827/195375984-18dcc6c9-ca30-428c-be11-cb92a4424a8d.png)

**Browser:**
 Chrome - Version 105.0.5195.127 (Official Build) (64-bit)

**Comment by dandavies99** [comment]
Closed in #208
