### ISSUE TITLE
Windows compatibility for Docker container build

### ISSUE THREAD

**Issue by CWestICL** [ImperialCollegeLondon/Faraday-liionsden#210]
**Issue**
Attempting to run `docker-compose up --build` will result in an issue for Windows users as Docker won't be able to locate the current `init.sh` and `install_ssh.sh` files. This is due to different line ending formats between Windows files and Mac/Linux files.

**Solution**
The line endings can be converted to the proper format during the build itself if some commands are added to the Dockerfile. This should hopefully solve the issue for Windows users and leave Mac/Linux users unaffected.

**Comment by dandavies99** [comment]
Solved in #212
