### ISSUE TITLE
Don't save EDF if UpdateDataFileForm is invalid

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/Faraday-liionsden#221]
Just been testing and noticed that when uploading an invalid settings or binary file when editing existing experiment data, the files are still uploaded despite the error message flagging them. Isn't an issue for new experiment data as it successfully blocks the upload there.

Changes have been merged already so I guess this should be put into a new issue?

_Originally posted by @CWestICL in https://github.com/ImperialCollegeLondon/Faraday-liionsden/issues/215#issuecomment-1326242215_

Aha! Link: https://imperial-college-ict.aha.io/requirements/RSE-132-21

**Comment by dandavies99** [comment]
This is a more general problem in that it affects other fields too. If you update e.g. the notes field as well, those changes are applied to the model even if the form is invalid. 

We don't see this behaviour with other models e.g. Experiment, if you change the name but give an invalid (too short) summary, the new name is _not_ updated. 

The `post()` method of the `UpdateDataFileView` is overridden from the `post()` method of `UpdateDataInlineView`. The different behaviour must come from the way in which the form is defined.

**Comment by dandavies99** [comment]
As far as I can tell, the object is saved when `form.is_valid()` is called within `UpdateDataFileView`, regardless of what is returned by that method.

**Comment by dandavies99** [comment]
I've just spotted that in the `clean` method of the `ExperimentDataFile` model there is: 

```
# This needs to be reviewed to avoid a recursion loop
            self.save()
```

I don't think this is normal and suspect this is being called when `form.is_valid()` is evaluated.
